### ISSUE TITLE
Insertion ans search in trie

### ISSUE THREAD

**Issue by ritweekraj2802** [Nihal-Priyadarshi/Hacktoberfest2021#140]
I want to add this problem in scripts section.
Please assign to me.
Thank you

**Comment by Nihal-Priyadarshi** [comment]
> I want to add this problem in scripts section. Please assign to me. Thank you

fork this repo, do your changes and make a PR, I'll merge it

**Comment by ritweekraj2802** [comment]
Please accept MY PR .
Thank you

**Comment by ritweekraj2802** [comment]
@Nihal-Priyadarshi Please accept my PR.
I have participated in Hacktoberfest2021.
Thank you
