### ISSUE TITLE
N QUEEN PROBLEM 

### ISSUE THREAD

**Issue by ritweekraj2802** [Nihal-Priyadarshi/Hacktoberfest2021#143]
I want to add "N QUEEN PROBLEM" in script section.

Please allow me to do so.
I have participated in HACKTOBERFEST2021.
THANK YOU

**Comment by saketmundra** [comment]
I know how to solve N queen problem in java.
Please allow me to do so for Hacktoberfest 2021.
ThankYou

**Comment by ritweekraj2802** [comment]
@Nihal-Priyadarshi Please accept my PR which I send to u.
Thank you

**Comment by manish866** [comment]
Please assign me I will do it in java
